#!/bin/bash

# Watches directory for changes and restarts
# automatically if the coffeescript compiler crashes.

trap 'exit' 2 # Trap SIGINT or we won't be able to exit. :)
mocha --compilers coffee:coffee-script test.coffee --watch --growl --reporter nyan || growlnotify --message "Test process is crashing." --wait;exec $0